[build-system]
requires = ["setuptools", "wheel", "Cython"]

[project]
name = "BenchSyntaxLab"
version = "0.0.2"
authors = [{name = "Arthur Carvalho", email = "arthurbcarvalho@gmail.com"}]
readme = "README.md"
requires-python = "<=3.11" # not sure